version: "3.7"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      - node.ml=false
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.license_management.enabled=false
      - xpack.rollup.enabled=false
      - map.includeElasticMapsService=false
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - apm

networks:
  apm:
    external: true